FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# CN 18/19 - Grupo 9

An API based on data taken from data.police.uk for Cloud Computing subject in FCUL

## Police Force Collection [/dataset/forces]

### Get Police Forces [GET /dataset/forces]

Returns a list of police forces.

+ Response 200 (application/json)

        {
            [
                {
                    "id": "avon-and-somerset",
                    "name": "Avon and Somerset Constabulary"
                },
                {
                    "id": "bedfordshire",
                    "name": "Bedfordshire Police"
                },
                {
                    "id": "cambridgeshire",
                    "name": "Cambridgeshire Constabulary"
                }
            ]
        }

### Get Police Force Info [GET /dataset/forces/{id}]

Returns the information for a Specific Force from its specified ID

+ Response 200 (application/json)

        {
            "description": "A police service for everyone",
            "url": "http://www.leics.police.uk/",
            "engagement_methods": [
                {
                    "url": "http://www.facebook.com/pages/Leicester/Leicestershire-Police/76807881169",
                    "description": "Become friends with Leicestershire Constabulary",
                    "title": "Facebook"
                },
                {
                    "url": "http://www.twitter.com/leicspolice",
                    "description": "Keep up to date with Leicestershire Constabulary on Twitter",
                    "title": "Twitter"
                },
                {
                    "url": "http://www.youtube.com/leicspolice",
                    "description": "See Leicestershire Constabulary's latest videos on YouTube",
                    "title": "YouTube"
                },
                {
                    "url": "http://www.leics.police.uk/rss/",
                    "description": "Keep informed with Leicestershire Constabulary's RSS feed",
                    "title": "RSS"
                }
            ],
            "telephone": "0116 222 2222",
            "id": "leicestershire",
            "name": "Leicestershire Constabulary"
        }

### Get Police Force Info [GET /dataset/forces/{id}/people]

Returns the list of senior officers for a Specific Force from its specified ID

+ Response 200 (application/json)

        {
            [
                {
                    "bio": "Roger joined Lincolnshire Police in 1988 having attended Queen Elizabeth Grammar School",
                    "contact_details": {
                        "twitter": "http://www.twitter.com/ACCCLeicsPolice"
                    },
                    "name": "Roger Bannister",
                    "rank": "Assistant Chief Officer (Crime)"
                }
            ]
        }